/**
 * AETHER-Generated Playwright-Java Test
 * Requirement: REQ-BANK-AUTH-001 — Banking Login Functionality
 * Test Suite:  Banking_Login_TC_1 (TC_001 – TC_008)
 * Framework:   playwright-java + TestNG + ExtentReports
 *
 * Source document: input/Banking_Login_TC_1.pdf
 * Generated by:    AETHER Automation Code Generator (Stage 4)
 * Framework:       playwright-java
 *
 * Compliance rules satisfied:
 *   PJ-001  Playwright/Browser lifecycle via PlaywrightManager
 *   PJ-002  BrowserContext per test method (isolated state)
 *   PJ-003  Page per test method
 *   PJ-004  Page Object Model (BankingLoginPage, BankingDashboardPage)
 *   PJ-005  CSS / ID locators only
 *   PJ-006  Explicit waits — no Thread.sleep
 *   PJ-007  No hardcoded credentials — ConfigReader only
 *   PJ-008  validate() guard before every test
 *   PJ-009  Extends BaseTest
 *   PJ-010  BeforeMethod / AfterMethod lifecycle
 *   PJ-011  All assertions via TestNG Assert + TestReporter
 *   PJ-012  Traceability tags on every assertion
 *   PJ-013  1:1:1 manual step → test step → traceability comment
 */
package com.aether.tests.functional.banking;

import com.aether.framework.core.BaseTest;
import com.aether.framework.core.ConfigReader;
import com.aether.framework.core.TestReporter;
import com.aether.pages.banking.BankingDashboardPage;
import com.aether.pages.banking.BankingLoginPage;
import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * Banking Login test suite — TC_001 through TC_008.
 *
 * Each @Test method corresponds to one manual test case from
 * Banking_Login_TC_1.pdf (input/Banking_Login_TC_1.pdf).
 *
 * Test execution order:
 *   TC_001 — Valid Login (username + password)
 *   TC_002 — Valid Login with OTP (MFA flow)
 *   TC_003 — Invalid username
 *   TC_004 — Invalid password
 *   TC_005 — Both credentials invalid
 *   TC_006 — Empty username
 *   TC_007 — Empty password
 *   TC_008 — Both fields empty
 */
public class Rev1_WA_Banking_Login extends BaseTest {

    // ── Page Objects ──────────────────────────────────────────────────────────
    private BankingLoginPage     bankingLoginPage;
    private BankingDashboardPage bankingDashboardPage;

    // ── Test Data (from ConfigReader — no hardcoded credentials) ──────────────
    private String validUsername;
    private String validPassword;
    // TC_002's first factor. Separate from the pair above because the second factor is a
    // property of the *user* in mock_aut, as it would be in a real bank: one pair cannot
    // both go straight to the dashboard (TC_001) and stop at the OTP page (TC_002). See
    // the note in config.properties and ADR §6.27.
    private String mfaUsername;
    private String mfaPassword;
    private String validOtp;
    private String invalidUsername;
    private String invalidPasswordUser;
    private String invalidPassword;
    private String bothInvalidUsername;
    private String bothInvalidPassword;

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    @BeforeMethod(alwaysRun = true)
    public void setUp() {
        // Page objects are created after openPage() sets this.page in BaseTest
        bankingLoginPage     = new BankingLoginPage(page);
        bankingDashboardPage = new BankingDashboardPage(page);

        validUsername        = ConfigReader.get("banking.valid.username");
        validPassword        = ConfigReader.get("banking.valid.password");
        mfaUsername          = ConfigReader.get("banking.mfa.username");
        mfaPassword          = ConfigReader.get("banking.mfa.password");
        validOtp             = ConfigReader.get("banking.valid.otp", "123456");
        invalidUsername      = ConfigReader.get("banking.invalid.username");
        invalidPasswordUser  = ConfigReader.get("banking.invalid.password.user");
        invalidPassword      = ConfigReader.get("banking.invalid.password");
        bothInvalidUsername  = ConfigReader.get("banking.both.invalid.username");
        bothInvalidPassword  = ConfigReader.get("banking.both.invalid.password");

        // Navigate to banking login page before each test
        page.navigate(ConfigReader.getBaseUrl());
        bankingLoginPage.validate();
    }

    @AfterMethod(alwaysRun = true, dependsOnMethods = {})
    public void reportStatus(ITestResult result) {
        if (result.getStatus() == ITestResult.FAILURE) {
            TestReporter.fail("TEST FAILED: " + result.getName());
        } else if (result.getStatus() == ITestResult.SUCCESS) {
            TestReporter.pass("TEST PASSED: " + result.getName());
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TC_001 — Valid Login (username + password)
    // Manual Steps:
    //   1. Open login page
    //   2. Enter valid username
    //   3. Enter valid password
    //   4. Click Login
    // Expected: User redirected to dashboard
    // ─────────────────────────────────────────────────────────────────────────

    @Test(description = "TC_001: Valid login — username and password",
          priority = 1,
          groups = {"smoke", "regression", "banking-login"})
    public void tc001_validLogin() {
        TestReporter.startTest("TC_001: Valid login — username and password",
            "Requirement: REQ-BANK-AUTH-001 | Banking_Login_TC_1.pdf TC_001");

        // Step 100: Verify login page is displayed
        // Traceability: TC_001 | Step 100: Login form visible
        TestReporter.step(100, "Verify Banking Login page is displayed");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: Banking Login page displayed [TC_001]",
                "FAILURE: Banking Login page not displayed [TC_001]"),
            "Banking Login page must be displayed before interacting"
        );

        // Step 200: Enter valid username
        // Traceability: TC_001 | Step 200: Valid username entered
        TestReporter.step(200, "Enter valid username: " + validUsername);
        bankingLoginPage.enterUsername(validUsername);

        // Step 300: Enter valid password
        // Traceability: TC_001 | Step 300: Valid password entered
        TestReporter.step(300, "Enter valid password");
        bankingLoginPage.enterPassword(validPassword);

        // Step 400: Click Login button
        // Traceability: TC_001 | Step 400: Submit credentials
        TestReporter.step(400, "Click Login button");
        bankingLoginPage.clickLoginButton();

        // Step 500: Verify redirect to Banking Dashboard
        // Traceability: TC_001 | Step 500: Dashboard must be visible
        TestReporter.step(500, "Verify redirect to Banking Dashboard");
        boolean dashboardLoaded = bankingDashboardPage.validate();
        Assert.assertTrue(
            TestReporter.assertCondition(dashboardLoaded,
                "SUCCESS: Banking Dashboard displayed after valid login [TC_001]",
                "FAILURE: Dashboard not displayed after login [TC_001]"),
            "User must be redirected to Banking Dashboard on valid login"
        );

        // Step 600: Verify URL contains authenticated route
        // Traceability: TC_001 | Step 600: URL reflects authenticated state
        TestReporter.step(600, "Verify URL reflects authenticated route");
        String currentUrl = page.url();
        boolean urlOk = currentUrl.contains("dashboard") ||
                        currentUrl.contains("home")      ||
                        currentUrl.contains("account");
        Assert.assertTrue(
            TestReporter.assertCondition(urlOk,
                "SUCCESS: URL='" + currentUrl + "' reflects authenticated route [TC_001]",
                "FAILURE: URL='" + currentUrl + "' does not reflect authenticated route [TC_001]"),
            "URL must reflect authenticated application state after login"
        );

        // Step 700: Verify logged-in username shown on dashboard
        // Traceability: TC_001 | Step 700: Username displayed
        TestReporter.step(700, "Verify logged-in username is displayed on dashboard");
        String displayedUser = bankingDashboardPage.getLoggedInUsername();
        Assert.assertFalse(
            TestReporter.assertCondition(displayedUser.isEmpty(),
                "FAILURE: No username displayed on dashboard [TC_001]",
                "SUCCESS: Logged-in username displayed='" + displayedUser + "' [TC_001]"),
            "Username must be shown on the Banking Dashboard"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TC_002 — Valid Login with OTP (MFA flow)
    // Manual Steps:
    //   1. Enter valid credentials
    //   2. Click Login
    //   3. Enter valid OTP
    //   4. Submit
    // Expected: Login successful, user redirected securely
    // ─────────────────────────────────────────────────────────────────────────

    @Test(description = "TC_002: Valid login with OTP (MFA two-factor authentication)",
          priority = 2,
          groups = {"regression", "banking-login", "mfa"})
    public void tc002_validLoginWithOtp() {
        TestReporter.startTest("TC_002: Valid login with OTP",
            "Requirement: REQ-BANK-AUTH-001 | Banking_Login_TC_1.pdf TC_002");

        // Step 100: Verify login page is displayed
        // Traceability: TC_002 | Step 100: Login form visible
        TestReporter.step(100, "Verify Banking Login page is displayed");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: Banking Login page displayed [TC_002]",
                "FAILURE: Banking Login page not displayed [TC_002]"),
            "Banking Login page must be displayed"
        );

        // Step 200: Enter valid credentials and click Login
        // Traceability: TC_002 | Step 200: First-factor authentication
        TestReporter.step(200, "Enter valid MFA-enrolled credentials '" + mfaUsername
            + "' and click Login (first factor)");
        bankingLoginPage.loginFirstFactor(mfaUsername, mfaPassword);

        // Step 300: Verify OTP verification page is displayed
        // Traceability: TC_002 | Step 300: OTP page shown after first factor
        TestReporter.step(300, "Verify OTP verification page is displayed");
        boolean otpPageDisplayed = bankingLoginPage.validateOtpPage();
        Assert.assertTrue(
            TestReporter.assertCondition(otpPageDisplayed,
                "SUCCESS: OTP verification page displayed [TC_002]",
                "FAILURE: OTP page not displayed after valid first-factor [TC_002]"),
            "OTP verification page must appear after first-factor login"
        );

        // Step 400: Enter valid OTP and submit
        // Traceability: TC_002 | Step 400: OTP submitted
        TestReporter.step(400, "Enter valid OTP: " + validOtp + " and submit");
        bankingLoginPage.submitOtp(validOtp);

        // Step 500: Verify redirect to Banking Dashboard (secure)
        // Traceability: TC_002 | Step 500: Secure redirect after MFA
        TestReporter.step(500, "Verify secure redirect to Banking Dashboard after OTP");
        boolean dashboardLoaded = bankingDashboardPage.validate();
        Assert.assertTrue(
            TestReporter.assertCondition(dashboardLoaded,
                "SUCCESS: Banking Dashboard displayed after MFA login [TC_002]",
                "FAILURE: Dashboard not displayed after OTP submission [TC_002]"),
            "User must be redirected securely to Banking Dashboard after OTP"
        );

        // Step 600: Verify URL contains authenticated route
        // Traceability: TC_002 | Step 600: Authenticated URL
        TestReporter.step(600, "Verify URL reflects secure authenticated route");
        String currentUrl = page.url();
        boolean urlOk = currentUrl.contains("dashboard") ||
                        currentUrl.contains("home")      ||
                        currentUrl.contains("account");
        Assert.assertTrue(
            TestReporter.assertCondition(urlOk,
                "SUCCESS: URL='" + currentUrl + "' reflects authenticated route [TC_002]",
                "FAILURE: URL='" + currentUrl + "' does not reflect authenticated route [TC_002]"),
            "URL must reflect authenticated state after MFA completion"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TC_003 — Invalid username
    // Manual Steps:
    //   1. Enter invalid username + valid password
    // Expected: Error message "Invalid username or password"
    // ─────────────────────────────────────────────────────────────────────────

    @Test(description = "TC_003: Invalid login — invalid username with valid password",
          priority = 3,
          groups = {"regression", "banking-login", "negative"})
    public void tc003_invalidUsername() {
        TestReporter.startTest("TC_003: Invalid login — invalid username",
            "Requirement: REQ-BANK-AUTH-001 | Banking_Login_TC_1.pdf TC_003");

        // Step 100: Verify login page is displayed
        // Traceability: TC_003 | Step 100: Pre-condition — login page visible
        TestReporter.step(100, "Verify Banking Login page is displayed");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: Banking Login page displayed [TC_003]",
                "FAILURE: Banking Login page not displayed [TC_003]"),
            "Login page must be visible"
        );

        // Step 200: Enter invalid username + valid password → click Login
        // Traceability: TC_003 | Step 200: Invalid credentials submitted
        TestReporter.step(200, "Enter invalid username '" + invalidUsername + "' + valid password → click Login");
        bankingLoginPage.login(invalidUsername, validPassword);

        // Step 300: Verify error message "Invalid username or password"
        // Traceability: TC_003 | Step 300: Error banner visible with correct text
        TestReporter.step(300, "Verify error banner is displayed");
        boolean errorDisplayed = bankingLoginPage.isErrorBannerDisplayed();
        Assert.assertTrue(
            TestReporter.assertCondition(errorDisplayed,
                "SUCCESS: Error banner displayed after invalid username [TC_003]",
                "FAILURE: No error banner after invalid username [TC_003]"),
            "Error banner must be visible on invalid login attempt"
        );

        TestReporter.step(310, "Verify error message text contains 'Invalid username or password'");
        String errorText = bankingLoginPage.getErrorBannerText();
        Assert.assertTrue(
            TestReporter.assertCondition(
                errorText.contains("Invalid username or password"),
                "SUCCESS: Error text='" + errorText + "' [TC_003]",
                "FAILURE: Error text='" + errorText + "' missing expected message [TC_003]"),
            "Error message must contain 'Invalid username or password'"
        );

        // Step 400: Verify user remains on login page
        // Traceability: TC_003 | Step 400: No redirect after failed login
        TestReporter.step(400, "Verify user remains on login page after failed login");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: User remains on login page after invalid username [TC_003]",
                "FAILURE: User was redirected away from login page [TC_003]"),
            "User must remain on login page after failed authentication"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TC_004 — Invalid password
    // Manual Steps:
    //   1. Enter valid username + invalid password
    // Expected: Error message displayed
    // ─────────────────────────────────────────────────────────────────────────

    @Test(description = "TC_004: Invalid login — valid username with invalid password",
          priority = 4,
          groups = {"regression", "banking-login", "negative"})
    public void tc004_invalidPassword() {
        TestReporter.startTest("TC_004: Invalid login — invalid password",
            "Requirement: REQ-BANK-AUTH-001 | Banking_Login_TC_1.pdf TC_004");

        // Step 100: Verify login page
        // Traceability: TC_004 | Step 100: Pre-condition
        TestReporter.step(100, "Verify Banking Login page is displayed");
        Assert.assertTrue(bankingLoginPage.validate(),
            "Login page must be visible [TC_004]");

        // Step 200: Enter valid username + invalid password → click Login
        // Traceability: TC_004 | Step 200: Wrong password
        TestReporter.step(200, "Enter valid username '" + invalidPasswordUser + "' with invalid password → click Login");
        bankingLoginPage.login(invalidPasswordUser, invalidPassword);

        // Step 300: Verify error message is displayed
        // Traceability: TC_004 | Step 300: Error banner visible
        TestReporter.step(300, "Verify error banner is displayed");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.isErrorBannerDisplayed(),
                "SUCCESS: Error banner displayed after invalid password [TC_004]",
                "FAILURE: No error banner after invalid password [TC_004]"),
            "Error banner must appear on wrong password"
        );

        TestReporter.step(310, "Verify error message text");
        String errorText = bankingLoginPage.getErrorBannerText();
        Assert.assertTrue(
            TestReporter.assertCondition(
                errorText.contains("Invalid username or password"),
                "SUCCESS: Error text='" + errorText + "' [TC_004]",
                "FAILURE: Error text='" + errorText + "' unexpected [TC_004]"),
            "Error message must contain 'Invalid username or password' [TC_004]"
        );

        // Step 400: Verify user remains on login page
        // Traceability: TC_004 | Step 400: No redirect
        TestReporter.step(400, "Verify user remains on login page");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: User remains on login page [TC_004]",
                "FAILURE: User was redirected away [TC_004]"),
            "User must stay on login page after failed login [TC_004]"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TC_005 — Both credentials invalid
    // Manual Steps:
    //   1. Enter invalid credentials
    // Expected: Login denied
    // ─────────────────────────────────────────────────────────────────────────

    @Test(description = "TC_005: Invalid login — both username and password invalid",
          priority = 5,
          groups = {"regression", "banking-login", "negative"})
    public void tc005_bothInvalid() {
        TestReporter.startTest("TC_005: Invalid login — both fields invalid",
            "Requirement: REQ-BANK-AUTH-001 | Banking_Login_TC_1.pdf TC_005");

        // Step 100: Verify login page
        // Traceability: TC_005 | Step 100: Pre-condition
        TestReporter.step(100, "Verify Banking Login page is displayed");
        Assert.assertTrue(bankingLoginPage.validate(),
            "Login page must be visible [TC_005]");

        // Step 200: Enter both invalid credentials → click Login
        // Traceability: TC_005 | Step 200: Both credentials invalid
        TestReporter.step(200, "Enter both invalid username '" + bothInvalidUsername + "' and invalid password → click Login");
        bankingLoginPage.login(bothInvalidUsername, bothInvalidPassword);

        // Step 300: Verify login denied — error banner shown
        // Traceability: TC_005 | Step 300: Login denied
        TestReporter.step(300, "Verify login is denied and error banner is shown");
        boolean errorDisplayed = bankingLoginPage.isErrorBannerDisplayed();
        Assert.assertTrue(
            TestReporter.assertCondition(errorDisplayed,
                "SUCCESS: Login denied — error banner displayed [TC_005]",
                "FAILURE: No error banner after both-invalid credentials [TC_005]"),
            "Error banner must appear when both credentials are invalid"
        );

        TestReporter.step(310, "Verify error message is non-empty");
        String errorText = bankingLoginPage.getErrorBannerText();
        Assert.assertFalse(
            TestReporter.assertCondition(errorText.isEmpty(),
                "FAILURE: Error message is empty [TC_005]",
                "SUCCESS: Error message='" + errorText + "' is non-empty [TC_005]"),
            "Error message must be non-empty after both-invalid login [TC_005]"
        );

        // Step 400: Verify user remains on login page
        // Traceability: TC_005 | Step 400: No redirect
        TestReporter.step(400, "Verify user remains on login page");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: User remains on login page [TC_005]",
                "FAILURE: User was redirected away [TC_005]"),
            "User must stay on login page after both-invalid login [TC_005]"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TC_006 — Empty username
    // Manual Steps:
    //   1. Leave username blank
    // Expected: Validation: "Username required"
    // ─────────────────────────────────────────────────────────────────────────

    @Test(description = "TC_006: Field validation — empty username shows 'Username required'",
          priority = 6,
          groups = {"regression", "banking-login", "field-validation"})
    public void tc006_emptyUsername() {
        TestReporter.startTest("TC_006: Field validation — empty username",
            "Requirement: REQ-BANK-AUTH-001 | Banking_Login_TC_1.pdf TC_006");

        // Step 100: Verify login page
        // Traceability: TC_006 | Step 100: Pre-condition
        TestReporter.step(100, "Verify Banking Login page is displayed");
        Assert.assertTrue(bankingLoginPage.validate(),
            "Login page must be visible [TC_006]");

        // Step 200: Leave username blank, enter a valid password
        // Traceability: TC_006 | Step 200: Username field intentionally empty
        TestReporter.step(200, "Leave username blank; enter a valid password");
        bankingLoginPage.clearUsername();
        bankingLoginPage.enterPassword("ValidPass123!");

        // Step 300: Click Login to trigger client-side validation
        // Traceability: TC_006 | Step 300: Trigger required-field validation
        TestReporter.step(300, "Click Login button to trigger required-field validation");
        bankingLoginPage.clickLoginButton();

        // Step 400: Verify 'Username required' inline error is displayed
        // Traceability: TC_006 | Step 400: Inline validation message visible
        TestReporter.step(400, "Verify 'Username required' validation message is displayed");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.isUsernameErrorDisplayed(),
                "SUCCESS: 'Username required' validation message displayed [TC_006]",
                "FAILURE: Username validation message not visible [TC_006]"),
            "Username required message must appear when username is empty"
        );

        TestReporter.step(410, "Verify validation message text contains 'username required'");
        String validationText = bankingLoginPage.getUsernameErrorText().toLowerCase();
        Assert.assertTrue(
            TestReporter.assertCondition(
                validationText.contains("username required"),
                "SUCCESS: Validation text='" + validationText + "' [TC_006]",
                "FAILURE: Validation text='" + validationText + "' does not contain 'username required' [TC_006]"),
            "Username validation message must contain 'username required'"
        );

        // Step 500: Verify user remains on login page
        // Traceability: TC_006 | Step 500: No redirect when validation fires
        TestReporter.step(500, "Verify form submission blocked — user stays on login page");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: User remains on login page when validation fires [TC_006]",
                "FAILURE: User was redirected despite empty username [TC_006]"),
            "User must remain on login page when required-field validation fires [TC_006]"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TC_007 — Empty password
    // Manual Steps:
    //   1. Leave password blank
    // Expected: Validation: "Password required"
    // ─────────────────────────────────────────────────────────────────────────

    @Test(description = "TC_007: Field validation — empty password shows 'Password required'",
          priority = 7,
          groups = {"regression", "banking-login", "field-validation"})
    public void tc007_emptyPassword() {
        TestReporter.startTest("TC_007: Field validation — empty password",
            "Requirement: REQ-BANK-AUTH-001 | Banking_Login_TC_1.pdf TC_007");

        // Step 100: Verify login page
        // Traceability: TC_007 | Step 100: Pre-condition
        TestReporter.step(100, "Verify Banking Login page is displayed");
        Assert.assertTrue(bankingLoginPage.validate(),
            "Login page must be visible [TC_007]");

        // Step 200: Enter valid username, leave password blank
        // Traceability: TC_007 | Step 200: Password field intentionally empty
        TestReporter.step(200, "Enter valid username '" + validUsername + "'; leave password blank");
        bankingLoginPage.enterUsername(validUsername);
        bankingLoginPage.clearPassword();

        // Step 300: Click Login to trigger validation
        // Traceability: TC_007 | Step 300: Trigger password required validation
        TestReporter.step(300, "Click Login button to trigger password required validation");
        bankingLoginPage.clickLoginButton();

        // Step 400: Verify 'Password required' inline error is displayed
        // Traceability: TC_007 | Step 400: Inline validation message visible
        TestReporter.step(400, "Verify 'Password required' validation message is displayed");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.isPasswordErrorDisplayed(),
                "SUCCESS: 'Password required' validation message displayed [TC_007]",
                "FAILURE: Password validation message not visible [TC_007]"),
            "Password required message must appear when password is empty"
        );

        TestReporter.step(410, "Verify validation message text contains 'password required'");
        String validationText = bankingLoginPage.getPasswordErrorText().toLowerCase();
        Assert.assertTrue(
            TestReporter.assertCondition(
                validationText.contains("password required"),
                "SUCCESS: Validation text='" + validationText + "' [TC_007]",
                "FAILURE: Validation text='" + validationText + "' does not contain 'password required' [TC_007]"),
            "Password validation message must contain 'password required'"
        );

        // Step 500: Verify user remains on login page
        // Traceability: TC_007 | Step 500: No redirect when validation fires
        TestReporter.step(500, "Verify form submission blocked — user stays on login page");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: User remains on login page [TC_007]",
                "FAILURE: User was redirected despite empty password [TC_007]"),
            "User must remain on login page when password validation fires [TC_007]"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TC_008 — Both fields empty
    // Manual Steps:
    //   1. Click login without any input
    // Expected: Required field validation shown for both fields
    // ─────────────────────────────────────────────────────────────────────────

    @Test(description = "TC_008: Field validation — both fields empty shows required messages",
          priority = 8,
          groups = {"regression", "banking-login", "field-validation"})
    public void tc008_bothFieldsEmpty() {
        TestReporter.startTest("TC_008: Field validation — both fields empty",
            "Requirement: REQ-BANK-AUTH-001 | Banking_Login_TC_1.pdf TC_008");

        // Step 100: Verify login page
        // Traceability: TC_008 | Step 100: Pre-condition
        TestReporter.step(100, "Verify Banking Login page is displayed");
        Assert.assertTrue(bankingLoginPage.validate(),
            "Login page must be visible [TC_008]");

        // Step 200: Clear both username and password fields
        // Traceability: TC_008 | Step 200: Both fields intentionally empty
        TestReporter.step(200, "Clear both username and password fields (leave them empty)");
        bankingLoginPage.clearUsername();
        bankingLoginPage.clearPassword();

        // Step 300: Click Login to trigger both required-field validations
        // Traceability: TC_008 | Step 300: Trigger both validations simultaneously
        TestReporter.step(300, "Click Login button to trigger both required-field validations");
        bankingLoginPage.clickLoginButton();

        // Step 400: Verify 'Username required' inline error
        // Traceability: TC_008 | Step 400: Username inline error visible
        TestReporter.step(400, "Verify 'Username required' validation message appears");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.isUsernameErrorDisplayed(),
                "SUCCESS: 'Username required' shown [TC_008]",
                "FAILURE: Username error not visible [TC_008]"),
            "Username required message must appear when both fields are empty [TC_008]"
        );

        TestReporter.step(410, "Verify username validation message text");
        String unameText = bankingLoginPage.getUsernameErrorText().toLowerCase();
        Assert.assertTrue(
            TestReporter.assertCondition(
                unameText.contains("username required"),
                "SUCCESS: Username error text='" + unameText + "' [TC_008]",
                "FAILURE: Username error text='" + unameText + "' unexpected [TC_008]"),
            "Username error must contain 'username required' [TC_008]"
        );

        // Step 500: Verify 'Password required' inline error
        // Traceability: TC_008 | Step 500: Password inline error visible
        TestReporter.step(500, "Verify 'Password required' validation message appears");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.isPasswordErrorDisplayed(),
                "SUCCESS: 'Password required' shown [TC_008]",
                "FAILURE: Password error not visible [TC_008]"),
            "Password required message must appear when both fields are empty [TC_008]"
        );

        TestReporter.step(510, "Verify password validation message text");
        String pwdText = bankingLoginPage.getPasswordErrorText().toLowerCase();
        Assert.assertTrue(
            TestReporter.assertCondition(
                pwdText.contains("password required"),
                "SUCCESS: Password error text='" + pwdText + "' [TC_008]",
                "FAILURE: Password error text='" + pwdText + "' unexpected [TC_008]"),
            "Password error must contain 'password required' [TC_008]"
        );

        // Step 600: Verify form submission is blocked — user stays on login page
        // Traceability: TC_008 | Step 600: No redirect when both validations fire
        TestReporter.step(600, "Verify form submission blocked — user stays on login page");
        Assert.assertTrue(
            TestReporter.assertCondition(bankingLoginPage.validate(),
                "SUCCESS: User remains on login page (both validations fired) [TC_008]",
                "FAILURE: User was redirected despite both fields being empty [TC_008]"),
            "User must remain on login page when both required-field validations fire [TC_008]"
        );
    }
}
